### ISSUE TITLE
Breaking changes since tidyr 1.0.0 implentation, nested list toJSON

### ISSUE THREAD

**Issue by HanjoStudy** [jeroen/jsonlite#292]
Hi recent updates to the tidyr [Package tidyr version 1.0.0] (or perhaps `purrr`) library has caused breaking changes when using a nested list and ` jsonlite::toJSON()`. This has resulted in a lot of headaches with APIs that use a nested structure.

See example below:

``` r
> library(tidyverse)
── Attaching packages ─────────────────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.1.0     ✔ purrr   0.3.0
✔ tibble  2.1.3     ✔ dplyr   0.8.3
✔ tidyr   1.0.0     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.4.0
── Conflicts ────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

(x <- mtcars %>% 
  tbl_df %>% 
  group_by(cyl) %>% 
  nest())
#> # A tibble: 3 x 2
#> # Groups:   cyl [3]
#>     cyl data                                                               
#>   <dbl> <S3: vctrs_list_of>                                                
#> 1     6 21.000, 21.000, 21.400, 18.100, 19.200, 17.800, 19.700, 160.000, 1…
#> 2     4 22.800, 24.400, 22.800, 32.400, 30.400, 33.900, 21.500, 27.300, 26…
#> 3     8 18.700, 14.300, 16.400, 17.300, 15.200, 10.400, 10.400, 14.700, 15…

# Problem
x  %>% jsonlite::toJSON()
#> Error: No method asJSON S3 class: vctrs_vctr

# temporary fix
x  %>% 
  mutate(data = map(data, data.frame)) %>% 
  jsonlite::toJSON() %>% invisible()
```
<sup>Created on 2019-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jeroen** [comment]
I am leaning towards to opinion that `vctrs_vctr` should inherit `list`, then your example works:

```r
class(x$data) <- c(class(x$data), 'list')
jsonlite::toJSON(x)
```

But if Hadley doesn't like this I am also fine with adding an `asJSON` method for ` vctrs_vctr`. 

I am surprised other packages with `list` methods don't run into this. Maybe it's because `asJSON` uses S4 methods (for historical reasons).

**Comment by jeroen** [comment]
This is now fixed in vctrs via: https://github.com/r-lib/vctrs/commit/bd28c27949bd37991e6df28261e361c806e8367e

**Comment by Fuco1** [comment]
Hi.  I have a tibble with no nested lists, just good old plain values, I'm still getting the `Error: No method asJSON S3 class: vctrs_vctr` error.  

I'm not sure how the fix above works or if it is relevant to my case.  I'm using vctrs 0.3.1 and latest jsonlite.  I'm using mongolite so the call is made from there.

I tried somewhat unsuccessfully to add the list class to the value, to define the methods for the `vctrs_vctr` class etc, but honestly I have no idea what I'm doing.

If you tell me how I can somehow pass you the dataframe/tibble, I can provide a repro case.
